### ISSUE TITLE
Warnings for sponsoring messages break build in some cases

### ISSUE THREAD

**Issue by kzu** [devlooped/SponsorLink#32]
Folks seem quite adamant that this is super bad. Specially in light of warnings-as-errors settings.

I hadn't considered that scenario, and having to configure that property as false not only breaks the regular dev flow but also can cause them to miss otherwise serious issues they should definitely be fixing before committing/pushing.

 Since Info diagnostics WILL show in the IDE (even if they aren't surfaced by default in the output window), it might be sufficient to turn them into info for now.

There was a suggestion that SponsorLink itself could instead be an IDE extension that provides this information in a different way (not to "abuse" the diagnostics feature), while also providing a place to turn on/off settings and perhaps navigate to sponsorable projects from an aggregated place? Not much of a fun of this since this would require an IDE extension also for Rider and I haven't done any extensibility work on that front.

**Comment by jaredpar** [comment]
> Folks seem quite adamant that this is super bad. Specially in light of warnings-as-errors settings.

Having worked on .NET compilers for quite some time I emphasize with this problem. Developers will respond strongly when upgrading a toolset, sdk, etc ... results in new warnings. 

> Since Info diagnostics WILL show in the IDE (even if they aren't surfaced by default in the output window), it might be sufficient to turn them into info for now.

We've had more success with this strategy. Developers are generally more receptive of new info messages in the IDE than diagnostics that show up during build and CI.

**Comment by kzu** [comment]
Thanks @jaredpar for the constructive feedback. SponsorLink never runs on CI nor CLI builds, so I guess an Info diagnostic (for now?) is the best course of action 👍

**Comment by TsengSR** [comment]
> Thanks @jaredpar for the constructive feedback. SponsorLink never runs on CI nor CLI builds, so I guess an Info diagnostic (for now?) is the best course of action 👍

Come with a more legitimate way to get compensated.

Offer SLAs, training or paid support. Something that gives companies confidence that if they have a problem that needs to be solved, it will be solved in a timely manner.

**Comment by jozefizso** [comment]
> Offer SLAs, training or paid support. Something that gives companies confidence that if they have a problem that needs to be solved, it will be solved in a timely manner.

THIS!

**Comment by kzu** [comment]
So both @TsengSR and @jozefizso think all the work GitHub has been putting into the whole Sponsors feature is illegitimate somehow? Please hurry up and let them know they are wasting precious resources: https://github.blog/2023-04-04-whats-new-with-github-sponsors/. It seems they are still working on it even AS OF NOW.

**Comment by jozefizso** [comment]
> So both @TsengSR and @jozefizso think all the work GitHub has been putting into the whole Sponsors feature is illegitimate somehow? Please hurry up and let them know they are wasting precious resources: https://github.blog/2023-04-04-whats-new-with-github-sponsors/. It seems they are still working on it even AS OF NOW. 

You are fantasizing.

**Comment by TsengSR** [comment]
> So both @TsengSR and @jozefizso think all the work GitHub has been putting into the whole Sponsors feature is illegitimate somehow? Please hurry up and let them know they are wasting precious resources: https://github.blog/2023-04-04-whats-new-with-github-sponsors/. It seems they are still working on it even AS OF NOW.

Stop putting words in other people mouth. 

The sponsors feature is what you call donations otherwise, which by their very definition are optional and usually not frequently used. 

You are the one complaining you don't get enough money for it. If you want a more constant money flow, that better covers compensates your efforts into the project, then offer SLA or paid support. 

Right know, you sound more like: 
>Waah wah, I put so many hours and only now I realized no one paid for it. How about i just blackmail 1000s of people for a quick cash-out and back out strategy instead of putting a bit effort for a more sustainable financing

Look at how other projects did successfully, like the authors of FluentAssertitions or EF Plus did. 

You just seem completely out of touch of the real world at this point. Did you ever worked in or for a company before? Theres shit tons of companies who pay for SLA and support, because they know if they encounter a critical bug or show stopper, they can get a solution within a business day or two. 

Companies fear nothing more than abandoned product (or rogue developers, like you became now), so they are more than willing to pay if they have it black on white, that the product will be continued to be maintained and they can access priority support if something happens.

Here, look at https://github.com/ag-grid/ag-grid. Licensed under MIT, enterprise under commercial and companies more than willingly pay https://www.ag-grid.com/license-pricing/ 999 bucks for development and ANOTHER 750$ bucks per >>DEPLOYMENT<< just to get that and its (imho) by FAR less useful than Moq **was**.

You are just lazy man. And since last week, also a criminal.

**Comment by kzu** [comment]
> Donations are for people, companies don't do donations.

Yet AWS donated to me 🤣 . And MS does it montly too (i.e. https://twitter.com/praeclarum/status/1415712787389550593). 

I get it that folks think things can't change. I'm just not willing to accept the status quo is unchangeable.

> Companies fear nothing more than abandoned product

Yet they depend on countless OSS projects that have no comercial license nor paid support. Puzzling!

**Comment by TsengSR** [comment]
> Yet they depend on countless OSS projects that have no comercial license nor paid support. Puzzling!
Yea dude, keep looking for excuses and try to blame everyone. Yet you are the only one responsible for commiting crimes, instead of building up a profitable business with a popular OSS library. 

What you get now, is ruined reputation and loss of any chance to turn this into a profitable business. Good job dude. /sarcasm off

**Comment by kzu** [comment]
#76 fixes this. Warnings can be raised that will never be considered errors by the IDE.
