### ISSUE TITLE
Support org-wide sponsorships

### ISSUE THREAD

**Issue by kzu** [devlooped/SponsorLink#47]
There were valid arguments in favor of organizations sponsoring the projects, rather than individuals.

I'm not entirely sold on this, but since SponsorLink is not about me, I think this should be accounted for and fully supported.

**Comment by psimsa** [comment]
I'm pretty sure that those benefiting from OSS the most are in fact organizations rather than individual developers, at least in terms of monetary gain. If I have to write my own libraries for work instead of using OSS, I get paid the same but the company wastes my productivity because I write Moq instead of solving business problems. I don't personally benefit much from using OSS at work, the company does because I don't have to reinvent the wheel and the company doesn't have to pay for it - to you or to me.

Sure, there are independent devs who actually gain money directly from using OSS. But I doubt they are in majority.

**Comment by kzu** [comment]
Well, as individuals and developers earning what's probably the highest salary tier even for juniors, we can't really say we can't afford to help other fellow devs which one day might be us too. Especially when sponsorships can be really really affordable (i.e. can even start at $1). Dunno...

**Comment by RyuuTDF** [comment]
> Well, as individuals and developers earning what's probably the highest salary tier even for juniors, we can't really say we can't afford to help other fellow devs which one day might be us too. Especially when sponsorships can be really really affordable (i.e. can even start at $1). Dunno...

Hi @kzu,
I've been following this for the past 2 weeks for 'my Corporate Overlords' and I've logged into my personal Github to post my suggestions for you about the org-wide point. As you've stated, the view you have is of a **freelance** developer, who has not been corporate for quite a while. From your other comments you seem to have contacts at various places like Microsoft and Amazon. My suggestion would be to talk to developers from those places, to get the view of the *corporate* developer and maybe get shown ways how other packages have already handled this. Implementing this is a big thing as @ewrogers pointed out here: https://github.com/moq/moq/issues/1396#issuecomment-1681030033 , corporate developers will be your majority type of users for any big package. 

To illustrate, let me try to give you an example of a corporate viewpoint.
We shall take a company with 250 developers. Let's say every team uses only 1 SponsorLink-package, so the company would have to pay $250 a month. Now keep in mind that this does NOT have to be the same SponsorLink-package, so that money could be going to a bunch of different projects.

This is were a blind spot in your freelance view comes in: **Administrative Overhead**.
a. In Europe & North America, with the exception of maybe specialized tools for a few employees, the company pays for the tools. Period, it does not matter if it is affordable. It's just way too much hassle for a company to deal with the Administrative Overhead of having all employees send in an invoice every month for each of their tools. This also means the developers have only an advisory role in what tooling is being used. 
b. Somebody is going to have to keep track who has to sponsor what, depending on what team they are in.
Developer's time is very expensive, they have to deliver value. Administrative employees are way cheaper, so they will have to spend time on this every month. So say that costs them $50 dollar a month.

So the company is now spending 300 dollars a month. For those 300 dollars they have the following options:
1. The company keeps using the SponsorLink-package. They'll have to spend time and money on extra administration for no additional benefit.
2. See if there is a package with corporate licensing that does the same thing. They'll have to pay the cost of the 'Migration Fee', but after that there is very low cost of administration and they might get things like SLAs, Premium Support, X years guaranteed updates

Unless you manage to minimize the Administrative Overhead-aspect, for example using @jelkevanhoorn's idea in https://github.com/devlooped/SponsorLink/issues/54 , to get it down to only $5 a month instead of $50, any company will choose option 2. Simply because: 'If I do have to pay, I am going to get the best value for my money.' and the 'Overlords' of the big majority of your users will force them to move away from any package using SponsorLink.

However, if it is $255 versus the $300, that $45 a month plus the 'Migration Fee' might convince them to stay on the SponsorLink-using package.

 Of course in this example there were only 250 developers. Multiply the amount of developers or SponsorLink-packages by 5 or 10 and all the numbers in this example go up very rapidly.

**Comment by kzu** [comment]
Done on https://github.com/devlooped/gh-sponsors/blob/main/src/Commands/SyncCommand.cs#L67-L129 which collects user's orgs, their sponsorships and associates them with the org's verified domain.
